GET http://localhost:8080/api/v1/users
###

GET http://localhost:8080/api/v1/users/10
###

# # Get locations with filters
# GET http://localhost:3001/locations?longitude=90&latitude>0
# ###

# # Get locations and sort
# GET http://localhost:3001/locations?sort=+longitude
# ###

# # Get locations with filters and sort
# GET http://localhost:3001/locations?latitude<0&longitude>0&sort=-latitude
# ###

DELETE http://localhost:8080/api/v1/users/12
###

POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "username": "jeppe",
  "first_name": 12,
  "email": "pekka@gmail.com"
}